import type { Metadata } from "next";
import {
	Geist,
	Geist_Mono,
	IBM_Plex_Mono,
	IBM_Plex_Sans,
	Inter,
} from "next/font/google";
import "./globals.css";

const interSans = IBM_Plex_Sans({
	variable: "--font-inter-sans",
	subsets: ["latin"],
});

const IBMMono = IBM_Plex_Mono({
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-ibm-plex-mono",
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${IBMMono.variable} ${interSans.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
